#version 430

{% include "particles/common/update_common.glsl" %}

void updateParticle(float t0, vec3 p0, vec3 v0, float radius) {
    const vec3 impulse = vec3(0.0, 5.0, 0.0);

    // Apply impulses // TODO: Before or after?
    vec3 v1 = v0 + impulse * deltaTime; // TODO: Euler integration?
    vec3 p1 = p0 + v1 * deltaTime; // TODO: Euler integration?
    
    emitParticle(t0 + deltaTime, p1, v1, radius);
}